sudo: required
services:
  -docker

before_install:
  - docker build -t simplygwee/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true simplygwee/docker-react npm run test -- --coverage