sudo: required
services:
  -docker

before_install:
  - docker build -t simplygwee/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true simplygwee/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-944427285131"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"